Improve message in error log
Prints error as JSON instead of just `[object Object]`.

Before:

```
  debugSource=[object Object]
Error: unknown type: /size
```

After:

```
  debugSource={
  "description": "Size in pixels of the image",
  "type": "/size"
}
Error: unknown type: /size
```